import type { 
  Workspace, 
  SocialPost, 
  PostVersion, 
  PostComment, 
  PostApproval, 
  Approver, 
  Integration 
} from '@/types/marketing';

// Mock Workspaces
export const mockWorkspaces: Workspace[] = [
  {
    id: 'ws-1',
    name: 'Livonius Marketing',
    slug: 'livonius',
    logo_url: undefined,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ws-2',
    name: 'Tech Startup Brasil',
    slug: 'tech-startup',
    logo_url: undefined,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'ws-3',
    name: 'E-commerce Store',
    slug: 'ecommerce',
    logo_url: undefined,
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-02-01T00:00:00Z',
  },
];

// Mock Social Posts
export const mockPosts: SocialPost[] = [
  {
    id: 'post-1',
    workspace_id: 'ws-1',
    title: 'Lançamento do novo produto de IA',
    content: 'Estamos empolgados em anunciar o lançamento do nosso mais novo produto de inteligência artificial! 🚀\n\nCom recursos avançados de processamento de linguagem natural, nosso produto vai revolucionar a forma como você interage com tecnologia.\n\n#IA #Tecnologia #Inovação',
    excerpt: 'Anúncio do lançamento do novo produto de IA',
    status: 'PUBLISHED',
    channels: ['instagram', 'linkedin'],
    media_urls: ['https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800'],
    scheduled_at: '2024-01-10T10:00:00Z',
    published_at: '2024-01-10T10:00:00Z',
    author_id: 'user-1',
    author_name: 'Maria Silva',
    approval_token: 'token-1',
    created_at: '2024-01-08T10:00:00Z',
    updated_at: '2024-01-10T10:00:00Z',
  },
  {
    id: 'post-2',
    workspace_id: 'ws-1',
    title: 'Dicas de produtividade para 2024',
    content: '5 dicas essenciais para aumentar sua produtividade em 2024:\n\n1. Organize suas tarefas com método GTD\n2. Use técnica Pomodoro\n3. Elimine distrações digitais\n4. Priorize sono de qualidade\n5. Pratique mindfulness\n\n#Produtividade #2024 #Dicas',
    excerpt: 'Dicas de produtividade para o novo ano',
    status: 'SCHEDULED',
    channels: ['instagram', 'facebook', 'linkedin'],
    media_urls: ['https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800'],
    scheduled_at: '2024-01-20T14:00:00Z',
    author_id: 'user-1',
    author_name: 'Maria Silva',
    approval_token: 'token-2',
    created_at: '2024-01-15T09:00:00Z',
    updated_at: '2024-01-18T11:00:00Z',
  },
  {
    id: 'post-3',
    workspace_id: 'ws-1',
    title: 'Case de sucesso: Cliente X',
    content: 'Conheça como a empresa X aumentou sua eficiência em 300% usando nossa solução de IA!\n\n📊 Resultados impressionantes\n⚡ Implementação em 2 semanas\n💰 ROI positivo no primeiro mês\n\nSaiba mais no link da bio!\n\n#CaseSuccess #IA #Resultados',
    excerpt: 'Case de sucesso com cliente X',
    status: 'APPROVED',
    channels: ['linkedin'],
    media_urls: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800'],
    author_id: 'user-2',
    author_name: 'João Santos',
    approval_token: 'token-3',
    created_at: '2024-01-16T08:00:00Z',
    updated_at: '2024-01-17T16:00:00Z',
  },
  {
    id: 'post-4',
    workspace_id: 'ws-1',
    title: 'Webinar: Tendências de Marketing Digital',
    content: '🎯 Participe do nosso webinar GRATUITO!\n\nTema: Tendências de Marketing Digital para 2024\n📅 Data: 25 de Janeiro\n⏰ Horário: 19h (Brasília)\n\nInscreva-se agora pelo link na bio!\n\n#Webinar #MarketingDigital #Gratuito',
    excerpt: 'Convite para webinar sobre marketing digital',
    status: 'IN_REVIEW_EXTERNAL',
    channels: ['instagram', 'facebook'],
    media_urls: ['https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=800'],
    author_id: 'user-1',
    author_name: 'Maria Silva',
    approval_token: 'token-4',
    created_at: '2024-01-17T10:00:00Z',
    updated_at: '2024-01-18T09:00:00Z',
  },
  {
    id: 'post-5',
    workspace_id: 'ws-1',
    title: 'Behind the scenes: Nossa equipe',
    content: 'Conheça a equipe por trás da magia! ✨\n\nNosso time é formado por profissionais apaixonados por tecnologia e inovação.\n\n#BehindTheScenes #Equipe #Cultura',
    excerpt: 'Post sobre a equipe da empresa',
    status: 'IN_REVIEW_INTERNAL',
    channels: ['instagram'],
    media_urls: ['https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800'],
    author_id: 'user-2',
    author_name: 'João Santos',
    approval_token: 'token-5',
    created_at: '2024-01-18T11:00:00Z',
    updated_at: '2024-01-18T11:00:00Z',
  },
  {
    id: 'post-6',
    workspace_id: 'ws-1',
    title: 'Novidade: Integração com WhatsApp',
    content: 'NOVIDADE! 🎉\n\nAgora você pode integrar nossa plataforma diretamente com o WhatsApp Business!\n\n✅ Atendimento automatizado\n✅ Respostas inteligentes\n✅ Análise de conversas\n\n#WhatsApp #Integração #Novidade',
    excerpt: 'Anúncio de nova integração',
    status: 'CHANGES_REQUESTED',
    channels: ['instagram', 'linkedin'],
    media_urls: ['https://images.unsplash.com/photo-1611746872915-64382b5c76da?w=800'],
    author_id: 'user-1',
    author_name: 'Maria Silva',
    approval_token: 'token-6',
    created_at: '2024-01-12T14:00:00Z',
    updated_at: '2024-01-14T10:00:00Z',
  },
  {
    id: 'post-7',
    workspace_id: 'ws-1',
    title: 'Dica rápida: Hashtags eficientes',
    content: '💡 Dica rápida!\n\nComo usar hashtags de forma eficiente:\n\n1. Use entre 5-10 hashtags\n2. Misture populares e nichadas\n3. Pesquise antes de usar\n4. Evite hashtags banidas\n\n#DicaDodia #SocialMedia #Hashtags',
    excerpt: 'Dica sobre uso de hashtags',
    status: 'DRAFT',
    channels: ['instagram'],
    media_urls: [],
    author_id: 'user-2',
    author_name: 'João Santos',
    approval_token: 'token-7',
    created_at: '2024-01-19T09:00:00Z',
    updated_at: '2024-01-19T09:00:00Z',
  },
  {
    id: 'post-8',
    workspace_id: 'ws-1',
    title: 'Retrospectiva 2023',
    content: '📊 Retrospectiva 2023\n\nEste ano foi incrível! Veja nossos números:\n\n🚀 500+ clientes atendidos\n💬 1M+ mensagens processadas\n⭐ 4.9 de avaliação média\n\nObrigado por fazer parte dessa jornada!\n\n#Retrospectiva #2023 #Gratidão',
    excerpt: 'Retrospectiva do ano de 2023',
    status: 'PUBLISHED',
    channels: ['instagram', 'facebook', 'linkedin'],
    media_urls: ['https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800'],
    published_at: '2023-12-28T18:00:00Z',
    author_id: 'user-1',
    author_name: 'Maria Silva',
    approval_token: 'token-8',
    created_at: '2023-12-26T10:00:00Z',
    updated_at: '2023-12-28T18:00:00Z',
  },
  {
    id: 'post-9',
    workspace_id: 'ws-1',
    title: 'Feliz Ano Novo!',
    content: '🎆 Feliz 2024! 🎆\n\nQue este novo ano traga muitas conquistas, inovações e sucesso para todos!\n\nEstamos prontos para fazer 2024 ainda melhor!\n\n#FelizAnoNovo #2024 #NovoAno',
    excerpt: 'Mensagem de ano novo',
    status: 'PUBLISHED',
    channels: ['instagram', 'facebook'],
    media_urls: ['https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=800'],
    published_at: '2024-01-01T00:01:00Z',
    author_id: 'user-1',
    author_name: 'Maria Silva',
    approval_token: 'token-9',
    created_at: '2023-12-30T15:00:00Z',
    updated_at: '2024-01-01T00:01:00Z',
  },
  {
    id: 'post-10',
    workspace_id: 'ws-1',
    title: 'Tutorial: Primeiros passos',
    content: '📚 Novo tutorial disponível!\n\nAprenda a configurar sua conta em 5 minutos:\n\n1. Acesse o painel\n2. Configure seu perfil\n3. Conecte suas redes\n4. Crie seu primeiro post\n5. Agende a publicação\n\nLink na bio!\n\n#Tutorial #Iniciante #Guia',
    excerpt: 'Tutorial para iniciantes',
    status: 'DRAFT',
    channels: ['instagram', 'linkedin'],
    media_urls: [],
    author_id: 'user-2',
    author_name: 'João Santos',
    approval_token: 'token-10',
    created_at: '2024-01-19T14:00:00Z',
    updated_at: '2024-01-19T14:00:00Z',
  },
];

// Mock Post Versions
export const mockVersions: PostVersion[] = [
  {
    id: 'ver-1',
    post_id: 'post-6',
    content: 'NOVIDADE! 🎉\n\nAgora temos integração com WhatsApp!\n\n#WhatsApp #Novidade',
    media_urls: [],
    version_number: 1,
    created_by: 'user-1',
    author_name: 'Maria Silva',
    created_at: '2024-01-12T14:00:00Z',
  },
  {
    id: 'ver-2',
    post_id: 'post-6',
    content: 'NOVIDADE! 🎉\n\nAgora você pode integrar nossa plataforma diretamente com o WhatsApp Business!\n\n✅ Atendimento automatizado\n✅ Respostas inteligentes\n\n#WhatsApp #Integração #Novidade',
    media_urls: ['https://images.unsplash.com/photo-1611746872915-64382b5c76da?w=800'],
    version_number: 2,
    created_by: 'user-1',
    author_name: 'Maria Silva',
    created_at: '2024-01-13T09:00:00Z',
  },
  {
    id: 'ver-3',
    post_id: 'post-6',
    content: 'NOVIDADE! 🎉\n\nAgora você pode integrar nossa plataforma diretamente com o WhatsApp Business!\n\n✅ Atendimento automatizado\n✅ Respostas inteligentes\n✅ Análise de conversas\n\n#WhatsApp #Integração #Novidade',
    media_urls: ['https://images.unsplash.com/photo-1611746872915-64382b5c76da?w=800'],
    version_number: 3,
    created_by: 'user-1',
    author_name: 'Maria Silva',
    created_at: '2024-01-14T10:00:00Z',
  },
];

// Mock Post Comments
export const mockComments: PostComment[] = [
  {
    id: 'com-1',
    post_id: 'post-6',
    author_id: 'user-2',
    author_name: 'João Santos',
    content: 'Ótimo post! Mas acho que podemos adicionar mais informações sobre os benefícios.',
    is_internal: true,
    created_at: '2024-01-13T10:00:00Z',
  },
  {
    id: 'com-2',
    post_id: 'post-6',
    author_id: 'user-1',
    author_name: 'Maria Silva',
    content: 'Adicionei os benefícios na versão 2. O que acha?',
    is_internal: true,
    created_at: '2024-01-13T11:00:00Z',
  },
  {
    id: 'com-3',
    post_id: 'post-6',
    author_name: 'Carlos (Cliente)',
    author_email: 'carlos@cliente.com',
    content: 'Gostei, mas acho que falta mencionar a análise de conversas que vocês mostraram na demo.',
    is_internal: false,
    created_at: '2024-01-14T09:00:00Z',
  },
  {
    id: 'com-4',
    post_id: 'post-4',
    author_id: 'user-2',
    author_name: 'João Santos',
    content: 'Excelente! Aprovado internamente. Vamos enviar para o cliente revisar.',
    is_internal: true,
    created_at: '2024-01-17T16:00:00Z',
  },
];

// Mock Post Approvals
export const mockApprovals: PostApproval[] = [
  {
    id: 'apr-1',
    post_id: 'post-1',
    approver_id: 'user-2',
    approver_name: 'João Santos',
    action: 'approved',
    comment: 'Excelente conteúdo!',
    is_external: false,
    created_at: '2024-01-09T14:00:00Z',
  },
  {
    id: 'apr-2',
    post_id: 'post-1',
    approver_email: 'cliente@empresa.com',
    approver_name: 'Pedro (Cliente)',
    action: 'approved',
    is_external: true,
    created_at: '2024-01-09T16:00:00Z',
  },
  {
    id: 'apr-3',
    post_id: 'post-6',
    approver_email: 'carlos@cliente.com',
    approver_name: 'Carlos (Cliente)',
    action: 'changes_requested',
    comment: 'Adicionar informação sobre análise de conversas',
    is_external: true,
    created_at: '2024-01-14T09:00:00Z',
  },
];

// Mock Approvers
export const mockApprovers: Approver[] = [
  {
    id: 'approver-1',
    workspace_id: 'ws-1',
    email: 'joao@livonius.com.br',
    name: 'João Santos',
    type: 'internal',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'approver-2',
    workspace_id: 'ws-1',
    email: 'ana@livonius.com.br',
    name: 'Ana Oliveira',
    type: 'internal',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'approver-3',
    workspace_id: 'ws-1',
    email: 'cliente@empresa.com',
    name: 'Pedro (Cliente)',
    type: 'external',
    is_active: true,
    created_at: '2024-01-05T00:00:00Z',
  },
  {
    id: 'approver-4',
    workspace_id: 'ws-1',
    email: 'carlos@cliente.com',
    name: 'Carlos (Cliente)',
    type: 'external',
    is_active: true,
    created_at: '2024-01-08T00:00:00Z',
  },
];

// Mock Integrations
export const mockIntegrations: Integration[] = [
  {
    id: 'int-1',
    workspace_id: 'ws-1',
    type: 'n8n',
    config: { webhook_url: 'https://n8n.example.com/webhook/marketing' },
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'int-2',
    workspace_id: 'ws-1',
    type: 'slack',
    config: { webhook_url: '' },
    is_active: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'int-3',
    workspace_id: 'ws-1',
    type: 'instagram_api',
    config: { access_token: '' },
    is_active: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'int-4',
    workspace_id: 'ws-1',
    type: 'whatsapp',
    config: { phone_number: '', api_key: '' },
    is_active: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];
